version: '3'
services:
    wikihelperservice:
        build: 
            dockerfile: ./WikiMediaHelperService/Dockerfile
            context: .
        ports: 
            - "2000:80"
    maphelperservice:
        build: 
            dockerfile: ./MapHelperService/Dockerfile
            context: .
        ports: 
            - "2001:80" 
    weatherhelperservice:
        build: 
            dockerfile: ./WeatherHelperService/Dockerfile
            context: .
        ports: 
            - "2002:80"              
    celestialbodyhelperservice:
        build: 
            dockerfile: ./CelestialBodyHelperService/Dockerfile
            context: .
        ports: 
            - "2003:80"    
    sqlserver:
        build: 
            context: ./SQLDatabase/
            args:
                PASSWORD: Pwd1234!
                DBNAME: SSDWebApiDb
        ports: 
            - "2004:1433" 
    astrophotographyhelperservice:
        build: 
            dockerfile: ./AstroPhotographyHelperService/Dockerfile
            context: .
        ports: 
            - "2005:80"    
        depends_on: 
            - sqlserver